// packages/types/src/index.ts

export interface ContactDetails {
  phone?: string;
  email?: string;
  website?: string;
}

export interface Service {
  id: string;
  name: string;
  description?: string;
  category?: string;
  contacts?: ContactDetails;
  // location?: string; // Example: GeoJSON point or address string
  // userProfileId?: string; // Link to user who listed it
}

export interface User {
  id: string;
  username: string;
  email?: string; // Assuming email might be part of user profile
  // other user fields
}

export interface BusinessListing extends Service {
  // Could extend Service or be a more specific type
  // For now, let's consider it similar to Service
}

// Example for a paginated response if that becomes a common pattern
export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}

// Placeholder for GraphQL query/mutation result types
// These would normally be generated by GraphQL Code Generator

export type Maybe<T> = T | null | undefined;

export interface GetServiceQuery {
  service?: Maybe<Pick<Service, 'id' | 'name' | 'description'>>;
}
export interface GetServiceQueryVariables {
  id: string;
}

export interface ListServicesQuery {
  listings?: Maybe<Array<Pick<Service, 'id' | 'name'>>>;
}
export interface ListServicesQueryVariables {
  filter?: Maybe<string>;
}
